// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcmzagiwhnptpqeuwgjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjbXphZ2l3aG5wdHBxZXV3Z2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzAyMzcsImV4cCI6MjA2MDEwNjIzN30.hcXrN2BCZZ9EN-pVrR7Rw0k-xhq0vVHoSXK62ugIk4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);